lectures/week04/rails/graphr/config/routes.rb
Graphr::Application.routes.draw do
  resources :graph_points

end

lectures/week04/rails/graphr/app/models/graph_point.rb
class GraphPoint < ActiveRecord::Base
end

lectures/week04/rails/graphr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

lectures/week04/rails/graphr/app/controllers/graph_points_controller.rb
class GraphPointsController < ApplicationController
  # GET /graph_points
  # GET /graph_points.xml
  # GET /graph_points.json
  def index
    @graph_points = GraphPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @graph_points }
      format.json { render :json => @graph_points }
    end
  end

  # GET /graph_points/1
  # GET /graph_points/1.xml
  # GET /graph_points/1.json
  def show
    @graph_point = GraphPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @graph_point }
      format.json { render :json => @graph_point }
    end
  end

  # GET /graph_points/new
  # GET /graph_points/new.xml
  def new
    @graph_point = GraphPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @graph_point }
    end
  end

  # GET /graph_points/1/edit
  def edit
    @graph_point = GraphPoint.find(params[:id])
  end

  # POST /graph_points
  # POST /graph_points.xml
  # POST /graph_points.json
  def create
    @graph_point = GraphPoint.new(params[:graph_point])

    respond_to do |format|
      if @graph_point.save
        format.html { redirect_to(@graph_point, :notice => 'Graph point was successfully created.') }
        format.xml  { render :xml => @graph_point, :status => :created, :location => @graph_point }
        format.json  { render :json => @graph_point, :status => :created, :location => @graph_point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @graph_point.errors, :status => :unprocessable_entity }
        format.json  { render :json => @graph_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /graph_points/1
  # PUT /graph_points/1.xml
  # PUT /graph_points/1.json
  def update
    @graph_point = GraphPoint.find(params[:id])

    respond_to do |format|
      if @graph_point.update_attributes(params[:graph_point])
        format.html { redirect_to(@graph_point, :notice => 'Graph point was successfully updated.') }
        format.xml  { head :ok }
        format.json { render :json => @graph_point }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @graph_point.errors, :status => :unprocessable_entity }
        format.json  { render :json => @graph_point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /graph_points/1
  # DELETE /graph_points/1.xml
  # DELETE /graph_points/1.json
  def destroy
    @graph_point = GraphPoint.find(params[:id])
    @graph_point.destroy

    respond_to do |format|
      format.html { redirect_to(graph_points_url) }
      format.xml  { head :ok }
      format.json { render :nothing => true }
    end
  end
end

lectures/week04/rails/graphr/app/helpers/application_helper.rb
module ApplicationHelper
end

lectures/week04/rails/graphr/app/helpers/graph_points_helper.rb
module GraphPointsHelper
end

lectures/week04/rails/graphr/app/views/graph_points/_form.html.erb
<%= form_for(@graph_point) do |f| %>
  <% if @graph_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graph_point.errors.count, "error") %> prohibited this graph_point from being saved:</h2>

      <ul>
      <% @graph_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x_coord %><br />
    <%= f.text_field :x_coord %>
  </div>
  <div class="field">
    <%= f.label :y_coord %><br />
    <%= f.text_field :y_coord %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lectures/week04/rails/graphr/app/views/graph_points/edit.html.erb
<h1>Editing graph_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @graph_point %> |
<%= link_to 'Back', graph_points_path %>

lectures/week04/rails/graphr/app/views/graph_points/index.html.erb
<h1>Listing graph_points</h1>

<table>
  <tr>
    <th>X coord</th>
    <th>Y coord</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @graph_points.each do |graph_point| %>
  <tr>
    <td><%= graph_point.x_coord %></td>
    <td><%= graph_point.y_coord %></td>
    <td><%= link_to 'Show', graph_point %></td>
    <td><%= link_to 'Edit', edit_graph_point_path(graph_point) %></td>
    <td><%= link_to 'Destroy', graph_point, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Graph point', new_graph_point_path %>

lectures/week04/rails/graphr/app/views/graph_points/new.html.erb
<h1>New graph_point</h1>

<%= render 'form' %>

<%= link_to 'Back', graph_points_path %>

lectures/week04/rails/graphr/app/views/graph_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>X coord:</b>
  <%= @graph_point.x_coord %>
</p>

<p>
  <b>Y coord:</b>
  <%= @graph_point.y_coord %>
</p>


<%= link_to 'Edit', edit_graph_point_path(@graph_point) %> |
<%= link_to 'Back', graph_points_path %>

lectures/week04/rails/graphr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Graphr</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>